### ISSUE TITLE
pre-formatting sql files

### ISSUE THREAD

**Issue by vitaly-t** [nlf/muckraker#17]
Since you guys are using [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html), just wanted to point at a significant improvement it received in [version 3.2.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.2.0) to allow static SQL pre-formatting (option `params`).

Might be useful to you, if you need to statically inject things like a schema name or some configurable table names ;)

See also [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) where it is used ;)

**Comment by nlf** [comment]
thanks for the info! i'll dig around later and see where i can apply it

**Comment by vitaly-t** [comment]
Was that feature of any use to you?

If not, I've just released [version 3.4.0](https://github.com/vitaly-t/pg-promise) that brings a few more useful features ;)
