### ISSUE TITLE
Better code example

### ISSUE THREAD

**Issue by vitaly-t** [nlf/muckraker#2]
I have submitted a PR for you just to show an example of better coding around pg-promise.

In addition, if you choose to use a full-feature promise library, like Bluebird, which I would recommend, you could replace:

```js
        .then(data=>{
            this.tables = data[0].map(table => table.table_name);
            this.routines = data[1].map(routine => routine.routine_name);
            return new Database(this.db, this.tables, this.routines, this.scripts);
        });
```
with
```js
        .spread((tables, routines)=>{
            this.tables = tables.map(table => table.table_name);
            this.routines = routines.map(routine => routine.routine_name);
            return new Database(this.db, this.tables, this.routines, this.scripts);
        });
```

See option [promiseLib](https://github.com/vitaly-t/pg-promise#promiselib)

**Comment by nlf** [comment]
thanks! i totally forgot about tasks and batching, that's really helpful. i do intend to stick with native promises, at least for the time being

**Comment by vitaly-t** [comment]
@nlf Check out the new [2.9.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.2.9.0) feature - [Query Files](https://github.com/vitaly-t/pg-promise#query-files) ;)

**Comment by nlf** [comment]
oh very nice! i'll definitely take advantage of that. thanks @vitaly-t

**Comment by vitaly-t** [comment]
Looking at the kinds of manipulation on query formatting: https://github.com/nlf/muckraker/blob/master/lib/table.js

[Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting) is the most flexible and efficient way to do that.

See examples:
* https://github.com/vitaly-t/pg-promise/issues/49
* https://github.com/vitaly-t/pg-promise/issues/42

**Comment by nlf** [comment]
hmm, interesting. i'll have to play with that and see if i can make it work

**Comment by vitaly-t** [comment]
Let me know if you're stuck, i will help ;)

**Comment by vitaly-t** [comment]
See if [this new demo](https://github.com/vitaly-t/pg-promise-demo) gives any better ideas ;)

**Comment by nlf** [comment]
the issue i'm having with deciding how best to implement the query formatting using the custom type formatting feature, is that i need to be able to inspect the metadata of the table (which i get as a result of a query) in order to determine which columns are json or jsonb to ensure they're formatted correctly.

**Comment by vitaly-t** [comment]
Data inspection is about the result of a query, while Custom Type formatting is about creating a query. Those are two opposite actions. I'm not sure what you mean - get access to metadata to verify data formatting, this sounds like a contradiction.

**Comment by nlf** [comment]
Separate queries. Upon connecting to the database I submit a query to get the metadata for all columns of all tables, I then use that information to create objects with basic methods for each table.

The methods for those tables use that metadata that I retrieved in the very first query to determine what column type each property is in future queries.

**Comment by vitaly-t** [comment]
This sounds complicated. I won't even ask what's that for :) I can only help with the custom formatting - it is to be able to convert any type, any object into a valid query. How this fits in with your design, I don't know :)

**Comment by vitaly-t** [comment]
Having thought about it, just wanted to add that it seems like an impossible task you are trying to accomplish.

When we convert JavaScript types into PostgreSQL, it is easy, there is a definitive logic there, one used by pg-promise also.

But when we get the data back, it is like a zoo, there are many ways in which the data can be converted back into JavaScript.

That's because the PostgreSQL list of types is immensely longer than that in JavaScript.

So if you are trying to automatically convert PostgreSQL types into JavaScript types,...I don't know how this is even possible... In fact, I don't think it is possible.

The only way to make it work is via explcit model binding, i.e. when you have a JavaScript model that represents a record, then you can automatically convert a record result back into such a model.

But without a pre-declared model like that - you can't really do that.

**Comment by nlf** [comment]
Ah yeah I think you're misunderstanding me. I'm trying to format the json into Postgres types. The main issue I have is with json columns, for instance an array is valid json but pg-promise (and every other library I've used) will convert an array into a Postgres array instead of formatting it as json. I inspect tables ahead of time so I can determine if user input needs to be formatted as a Postgres array or a json array before being sent to the database

**Comment by vitaly-t** [comment]
In this case you can easily wrap an array into a Custom Format Type, and tell it what should it produce - JSON or an array.

**Comment by vitaly-t** [comment]
Here's a complete example:
```js
var pgp = require('pg-promise');

function JSONArray(data, isArray) {
    this.formatDBType = function () {
        return isArray ? data : JSON.stringify(data);
    };
}

var data = ['one', 'two', 'three'];

var ja1 = new JSONArray(data, true);
var ja2 = new JSONArray(data, false);

pgp.as.format("$1", [ja1]); //> array['one','two','three']
pgp.as.format("$1", [ja2]); //> '["one","two","three"]'
```

**Comment by vitaly-t** [comment]
See the addition in version [3.1.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.1.0)... you can replace this:
```js
let query = `SELECT * FROM "$[_table^]"`;
```
with this:
```js
let query = `SELECT * FROM $[_table~]`;
```
