### ISSUE TITLE
Javascripts as `db/` scripts

### ISSUE THREAD

**Issue by latentflip** [nlf/muckraker#23]
Nlf and I discussed briefly being able to put javascript files in the scripts dir, and have them attached to the table too.

I had a quick start at hacking this out, and ran into some things that are probably worth discussing.
- how to pass the muckraker instance to the function? Apply it as `this` (which won't work if people use arrow fns) or pass it as the first arg?
- for a moment I was unsure whether a "table" function should be passed the table or the full muckraker instance, but I think it makes most sense for it to be the muckraker instance, as that's effectively how it works for sql scripts (you can select from any table)
- how to pass additional args? JS doesn't need named args like the sql scripts too, but perhaps for consistency, we should only support passing a single object argument?
- do we still want to use names to handle the `_one_` config? I'm thinking maybe yes, until we start doing it differently in sql too?

```
// trivial example 
module.exports = function (db, args) {
    return db.orgs.findOne({ name: args.org_name })
                  .then((org) => {
                    return db.users.update({ id: args.user_id }, { org_id: org.id });
                  });
};
```

**Comment by nlf** [comment]
closed in #28
